name: ESLint Fix
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-metadata:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    outputs:
      dependency-group: ${{ steps.metadata.outputs.dependency-group }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  create-pr:
    runs-on: ubuntu-latest
    needs: dependabot-metadata
    if: ${{needs.dependabot-metadata.outputs.dependency-group == 'eslint' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}    
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: npm ci
      - name: Lint Fix
        run: npm run lint-fix
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          path: ./
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ESLint --fix
          signoff: false
          branch: ci/eslint
          base: master
          delete-branch: true
          title: 'ESLint fix'
          body: |
            Lint fixes based on the latest version of ESLint.
          labels: |
            automated pr
          draft: false
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
