name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        check-latest: true
        node-version-file: '.nvmrc'
    - name: Install
      run: npm ci
    - name: Test
      run: npm test
