name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [14, 16, 18]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.version }}
      uses: actions/setup-node@v3
      with:
        check-latest: true
        node-version: ${{ matrix.version }}
    - name: Install
      run: npm ci
    - name: Test
      run: npm test
