name: Run OpenActive Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-validator-site:
    uses: openactive/openactive-test-suite/.github/workflows/test-and-publish.yml@master
    with:
      data-models_ref: ${{ github.ref }}
