name: Publish to npm

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.author.email, 'hello@openactive.io')"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
    - name: Identify
      run: |
        git config user.name OpenActive Bot
        git config user.email hello@openactive.io
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Install
      run: npm ci
    - name: Test
      run: npm test
    - name: Increment Version
      run: npm version patch
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: Push version update
      run: git push

  dispatch:
    needs: publish
    strategy:
      matrix:
        repo: ['OpenActive.NET', 'models-php', 'models-ruby', 'data-model-validator', 'openactive.github.io', 'developer-documentation']
    runs-on: ubuntu-latest
    steps:
      - name: Trigger tooling update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          repository: openactive/${{ matrix.repo }}
          event-type: data-models-update
